# Generated by Django 3.2.13 on 2022-11-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_articles_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='articles',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='articles',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='articles',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='articles',
            name='image_5',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
