# Generated by Django 3.2.13 on 2022-11-02 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_diaryimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiaryImage',
            new_name='Image',
        ),
    ]
