# Generated by Django 3.2.13 on 2022-11-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_rename_diaryimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='image_5',
        ),
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
