# Generated by Django 3.2.13 on 2022-11-02 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20221102_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='image1',
            new_name='image',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
