# Generated by Django 3.2.13 on 2022-11-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
